### ISSUE TITLE
Can't open on MacOS Catalina

### ISSUE THREAD

**Issue by sephie** [lekevicius/october30#3]
Apparent problem after installing MacOS Catalina.
I really enjoy these logos even though I'm not that big of an Apple fan. ;)

<img width="413" alt="Screenshot 2019-10-14 at 13 19 48" src="https://user-images.githubusercontent.com/1169263/66747676-64c1e300-ee85-11e9-9a41-75a0e74d03a2.png">

**Comment by mountainash** [comment]
Just as a comparison https://github.com/pedrommcarrasco/Brooklyn#readme doesn't do this [error message], so something looks odd about **october30**

**Comment by pcherna** [comment]
Under Catalina, after trying to install it you have to go to System Preferences > Security & Privacy > General tab. In the lower area it will say that you can't open October30.saver because it's from an unidentified developer. Select "Open Anyway" and then go back to screen savers, and it will work.

**Comment by pravingadakh** [comment]
Try

`xattr -d com.apple.quarantine /Users/yourUsername/Library/Screen\ Savers/October30.saver`
